function dataOut = importLedgerFile2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LOG062120213XFB3XFB2 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  LOG062120213XFB3XFB2 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  log062120213XFB3XFB2 = importfile("G:\SocialData\Behavior only\CohortXFB\6-21-2021\log06-21-2021(3-XFB3-XFB2).stateScriptLog", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Jan-2022 12:57:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "#";

% Specify column names and types
opts.VariableNames = ["Events", "Code"];
opts.VariableTypes = ["string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Events", "Code"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Events", "Code"], "EmptyFieldRule", "auto");

% Import the data
dataOut = readtable(filename, opts);




end